# Generated by Django 4.0.4 on 2022-05-28 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drug_review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugreview',
            name='date',
            field=models.DateField(),
        ),
    ]
