# Generated by Django 4.0.4 on 2022-05-28 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PharmaSales',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('datum', models.DateField()),
                ('mo1ab', models.FloatField()),
                ('mo1ae', models.FloatField()),
                ('no2ba', models.FloatField()),
                ('n02be', models.FloatField()),
                ('n05b', models.FloatField()),
                ('n05c', models.FloatField()),
                ('r03', models.FloatField()),
                ('r06', models.FloatField()),
                ('year', models.DateField()),
            ],
        ),
    ]
