# Generated by Django 4.0.4 on 2022-05-28 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharma', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmasales',
            name='year',
            field=models.PositiveIntegerField(),
        ),
    ]
